version: '3.9'

services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "5000:5000"
    environment:
      - USER_SERVICE_URL=http://user-service:5001
    depends_on:
      - user-service

  user-service:
    build:
      context: ./user-service
    ports:
      - "5001:5001"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SERVICE_ROLE=${SERVICE_ROLE}

  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - user-service
